//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVVD.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RVVD.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add periods.
        /// </summary>
        public static string MT_cb_AddPeriods {
            get {
                return ResourceManager.GetString("MT_cb_AddPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item returns.
        /// </summary>
        public static string MT_cb_AddReturns {
            get {
                return ResourceManager.GetString("MT_cb_AddReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve returns.
        /// </summary>
        public static string MT_cb_PreserveReturns {
            get {
                return ResourceManager.GetString("MT_cb_PreserveReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lower case.
        /// </summary>
        public static string MT_cbi_lowerCase {
            get {
                return ResourceManager.GetString("MT_cbi_lowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -none-.
        /// </summary>
        public static string MT_cbi_none {
            get {
                return ResourceManager.GetString("MT_cbi_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentance case..
        /// </summary>
        public static string MT_cbi_sentanceCase {
            get {
                return ResourceManager.GetString("MT_cbi_sentanceCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Case.
        /// </summary>
        public static string MT_cbi_titleCase {
            get {
                return ResourceManager.GetString("MT_cbi_titleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tOGGLE cASE.
        /// </summary>
        public static string MT_cbi_toggleCase {
            get {
                return ResourceManager.GetString("MT_cbi_toggleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPPER CASE.
        /// </summary>
        public static string MT_cbi_UpperCase {
            get {
                return ResourceManager.GetString("MT_cbi_UpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Text.
        /// </summary>
        public static string MT_Title {
            get {
                return ResourceManager.GetString("MT_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
    }
}
